### ISSUE TITLE
PDOS workchain failed with "bad Fermi energy"

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-quantumespresso#887] opened 2023-02-09 12:37 UTC
This can be reproduce by submit a calculation on SiO2 from example structure importer, band structure calculation in AiiDAlab-THEOS (settings: `insulator`, `moderate`).
The error is:

```
...
   Computing kpt #:  2701  of  2701
     total cpu time spent up to now is      360.2 secs
 
     ethr =  3.75E-12,  avg # of iterations = 22.7
     Message from routine efermit:
     internal error, cannot bracket Ef
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Error in routine tetra_weights (1):
     bad Fermi energy
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 
     stopping ...
```

The pw input and output is attached
[pw-303-pdos-error.in.txt](https://github.com/aiidateam/aiida-quantumespresso/files/10697151/pw-303-pdos-error.in.txt)
[pw-303-pdos-error.out.txt](https://github.com/aiidateam/aiida-quantumespresso/files/10697152/pw-303-pdos-error.out.txt)

**Comment by mbercx** [comment] 2023-02-09 17:29
This could be caused by not having enough bands in the `nscf` calculation. It seems `nbnd` was set explicitly to 16 here, which is the number of occupied KS states. Will try to reproduce and investigate.

**Comment by unkcpz** [comment] 2023-02-20 13:48
Hi @mbercx, if you get time can you investigate a bit on this? Let me know if you have clue on this and I can work on fixing that this week.

**Comment by mbercx** [comment] 2023-03-01 13:51
Ok, managed to reproduce it! Seems calculating _both_ bands and pdos causes the issue. Pretty sure this is related to the `QeAppWorkChain`, I'll look into it some more.

**Comment by mbercx** [comment] 2023-03-01 15:18
> Althogh, the development environment now is quite easy to start with aiidalab-launch I'd say

https://www.youtube.com/watch?v=PNsUgvkjviY

**Comment by mbercx** [comment] 2023-03-01 17:40
Closing since this is actually caused by an issue on the QEapp, see https://github.com/aiidalab/aiidalab-qe/issues/362

**Closed by mbercx** 2023-03-01 17:40 UTC
