### ISSUE TITLE
MatdynCalculation exception

### ISSUE THREAD

**Issue by mkotiuga** [aiidateam/aiida-quantumespresso#563] opened 2020-09-30 21:43 UTC
I submitted 16 matdyn calculations w/ a script, 2 were excepted, and were excepted again when retried. See below for one of them. The error is in the presubmit call with a validation error: 

`InputValidationError: You cannot specify explicitly the 'flfrc' key in the 'INPUT' namelist.
 `
However, 'flfrc' key is not being set (the input parameters are also below). Comparing to other matdyn calculations submitted by the script I cannot find a difference (or one with the results of the parent q2r calculations.)

```
(aiida) mkotiuga@theospc2:~/Desktop/BTO/BTO_5atom/PhononVolume/CTO$ verdi process list -p 1 -a|grep 52012
52012  4m ago     MatdynCalculation          ⨯ Excepted        Waiting for transport task: upload
(aiida) mkotiuga@theospc2:~/Desktop/BTO/BTO_5atom/PhononVolume/CTO$ verdi node show 52012
Property     Value
-----------  -----------------------------------------------------------------------------------------------------------------------------------------------------------
type         MatdynCalculation
state        Excepted <Traceback (most recent call last):
               File "/home/mkotiuga/.virtualenvs/aiida/lib/python3.6/site-packages/aiida/engine/processes/calcjobs/tasks.py", line 78, in do_upload
                 calc_info = process.presubmit(folder)
               File "/home/mkotiuga/.virtualenvs/aiida/lib/python3.6/site-packages/aiida/engine/processes/calcjobs/calcjob.py", line 314, in presubmit
                 calc_info = self.prepare_for_submission(folder)
               File "/home/mkotiuga/.virtualenvs/aiida/lib/python3.6/site-packages/aiida_quantumespresso/calculations/matdyn.py", line 73, in prepare_for_submission
                 calcinfo = super(MatdynCalculation, self).prepare_for_submission(folder)
               File "/home/mkotiuga/.virtualenvs/aiida/lib/python3.6/site-packages/aiida_quantumespresso/calculations/namelists.py", line 163, in prepare_for_submission
                 parameters = self.set_blocked_keywords(parameters)
               File "/home/mkotiuga/.virtualenvs/aiida/lib/python3.6/site-packages/aiida_quantumespresso/calculations/namelists.py", line 82, in set_blocked_keywords
                 'namelist.'.format(key, namelist))
             aiida.common.exceptions.InputValidationError: You cannot specify explicitly the 'flfrc' key in the 'INPUT' namelist.

             The above exception was the direct cause of the following exception:

             aiida.engine.processes.calcjobs.tasks.PreSubmitException: exception occurred in presubmit call
             >
pk           52012
uuid         11386531-88a1-4b8a-8cb3-54de7b269506
label        matdyn for calc uuid: 828067e9-7d50-44b9-913e-6faa01651f36 (pk: 50479) (aiida.calculations:quantumespresso.q2r)
description  matdyn for calc uuid: 828067e9-7d50-44b9-913e-6faa01651f36 (pk: 50479) (aiida.calculations:quantumespresso.q2r)
ctime        2020-09-30 21:24:50.843719+00:00
mtime        2020-09-30 21:25:24.652946+00:00
computer     [14] PizDaint_mr0_mc

Inputs              PK  Type
---------------  -----  ------------------
code             47925  Code
force_constants  51878  ForceConstantsData
kpoints          52011  KpointsData
parameters       52010  Dict

Log messages
---------------------------------------------
There are 1 log messages for this calculation
Run 'verdi process report 52012' to see them
(aiida) mkotiuga@theospc2:~/Desktop/BTO/BTO_5atom/PhononVolume/CTO$ verdi data dict show 52010
{
    "INPUT": {
        "asr": "simple"
    }
}
```

**Comment by giovannipizzi** [comment] 2020-10-01 08:42
Very weird...

I think the only way this happens is if the `set_blocked_keywords` method is called more than once.
Looking into it, I realise that it declared as a classmethod, while it's only used as a normal instance method.

Could this be a problem? That in the same worker, the first call actually sets something at the class level? 
Or anyway what could happen is that the same blocked keyword is added twice to the list, and the first time it also sets the default here:
https://github.com/aiidateam/aiida-quantumespresso/blob/59b957abdcb4b02e1745e262f8e2230566c65cc3/aiida_quantumespresso/calculations/namelists.py#L85
and so it complains when checking the second identical entry in the `cls._blocked_keywords`.

Consider also that we do this in the matdyn plugin:
https://github.com/aiidateam/aiida-quantumespresso/blob/59b957abdcb4b02e1745e262f8e2230566c65cc3/aiida_quantumespresso/calculations/matdyn.py#L74

Still, I'm not 100% sure of what is actually happening.

@mkotiuga one thing you could do is to add a print statement before this line
https://github.com/aiidateam/aiida-quantumespresso/blob/59b957abdcb4b02e1745e262f8e2230566c65cc3/aiida_quantumespresso/calculations/namelists.py#L80
and print `cls._blocked_keywords`. Then restart the daemon (`verdi daemon restart --reset`) and report back what will show up in the aiida deamon log if this happens again (or equivalently add the `cls._blocked_keywords` in the exception message).

Pinging @sphuber @greschd for suggestions on what could be happening

**Comment by sphuber** [comment] 2020-10-01 08:59
I think that `set_blocked_keywords` definitely should not be a class method, because it will affect all classes, whereas we want it to be an instance method, since `NamelistsCalculation` is supposed to be subclassed.

I think you are right though. The same entry is added multiple times to the class and so for a single worker at some point the `_blocked_keywords` class attribute may look something like:
```
NamelistsCalculation._blocked_keywords = [
    ('INPUT', 'flfrc', 'filename.txt'),
    ('INPUT', 'flfrc', 'filename.txt'),
]
```
and I think you are right that this would indeed just fall over in `set_blocked_keywords`. I think that turning that method into an instance method is a first step, but we still need to fix the rest of the logic I think. It doesn't really make sense that if you just add the same blocked keyword twice, that it would then fall over. Sure it doesn't make a whole lot of sense, but I don't think it should fail.

**Comment by mkotiuga** [comment] 2022-02-22 15:14
Ok, circling back to this as it is still an issue, and now I actually understand AiiDA well enough to understand what at @giovannipizzi and @sphuber said back in 2020. 

So before I remembered that this was the issue I had that prompted me just to run matdyn locally with a bash script (please withhold your judgement)  - also to avoid queuing a 30s job that can be run on 1 core - I looked into it a bit. Indeed 

`('INPUT', 'flfrc', 'filename.txt'),`

gets added to the `_blocked_keywords` twice, and this is what triggers the error. Due to the fact that `_set_blocked_keywords` is a class method when the daemon is restarted one job can run fine as `('INPUT', 'flfrc', 'filename.txt'),` has not been added yet. As a quick fix I removed the line:

https://github.com/aiidateam/aiida-quantumespresso/blob/59b957abdcb4b02e1745e262f8e2230566c65cc3/aiida_quantumespresso/calculations/matdyn.py#L74

and added 

` _FORCE_CONSTANTS_NAME = 'real_space_force_constants.dat'  <---new
_blocked_keywords = [
        ('INPUT', 'flfrq', _PHONON_FREQUENCIES_NAME),  # output frequencies
        ('INPUT', 'flvec', _PHONON_MODES_NAME),  # output displacements
        ('INPUT', 'fldos', _PHONON_DOS_NAME),  # output density of states
        ('INPUT', 'q_in_cryst_coord', True),  # kpoints always in crystal coordinates
        ('INPUT', 'flfrc',_FORCE_CONSTANTS_NAME)  <---new
]`

which works b/c I am always restarting from a Q2r ran with AiiDA, so the name of the force_constant_file is fixed there. In theory this could be a user input, so this fix would not work in general

**Comment by mkotiuga** [comment] 2022-02-22 15:22
pinging @mbercx as we would have to deal with this for any future phonon workchains....

**Comment by mbercx** [comment] 2022-03-06 21:31
Looking at the `set_blocked_keywords` code:

https://github.com/aiidateam/aiida-quantumespresso/blob/96356d3b767446dac3fef37b2d232b2ea4e50d89/aiida_quantumespresso/calculations/namelists.py#L72-L88

It's indeed clear that this will raise in case there are two identical tuples in `cls. _blocked_keywords`. However, I don't think the fact that this is a `classmethod` is the issue here. It simply uses the `_blocked_keywords ` class variable to set defaults in the `parameters` dictionary, and raises in case the blocked keyword has already been set. I also don't really understand how a class method would affect all classes more than an instance method would?

The problem is that the `_blocked_keywords` _class variable_ is mutated in the `prepare_for_submission` instance method of `MatdynCalculation`, in the line that both @giovannipizzi and @mkotiuga already showed:

https://github.com/aiidateam/aiida-quantumespresso/blob/96356d3b767446dac3fef37b2d232b2ea4e50d89/aiida_quantumespresso/calculations/matdyn.py#L74

Now, changing class variables is risky business, that has different behaviour in Python depending on how it is changed. The following example:

```python
class TestClass():

    class_variable = ['a', ]
    
    def add_to_classvar(self, element):
        self.class_variable.append(element)

alpha = TestClass()
beta = TestClass()
alpha.add_to_classvar('b')

print(f'alpha.class_variable: {alpha.class_variable}')
print(f'beta.class_variable: {beta.class_variable}')
```

Will return

```python
alpha.class_variable: ['a', 'b']
beta.class_variable: ['a', 'b']
```

So, _mutating_ the `class_variable` of `alpha` using the `add_to_classvar` _instance method_ will also change the `class_variable` of `beta`! I think this is what is happening here, in combination with the fact that `set_blocked_keywords` doesn't like duplicates. Note that changing the class variable by _assigning_ a value to it:

```python
alpha = TestClass()
beta = TestClass()
alpha.class_variable = 'A string!'

print(f'alpha.class_variable: {alpha.class_variable}')
print(f'beta.class_variable: {beta.class_variable}')

```

returns

```python
alpha.class_variable: A string!
beta.class_variable: ['a', 'b']
```

In this case a new instance of the variable is created and only assigned to the `alpha` instance.

---

So, I think the right approach is to avoid mutating class variables in any of the `NamelistsCalculation` subclasses. I'm still working on adapting the `MatDynCalculation` to allow for DOS calculations, will fix this issue along with those changes.

**Closed** 2022-05-13 07:19 UTC
Labels: type/bug, topic/calculations, priority/important
