### ISSUE TITLE
PwImmigrant does not parse bands

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida-quantumespresso#74] opened 2017-12-31 10:27 UTC
When importing a bands-calculation, the PwImmigrant does not create a BandsData instance.
This needs to be implemented and the documentation updated.

**Comment by lekah** [comment] 2018-01-01 12:50
Would the method calc._set_retrieve_temporary_list(retrieve_temporary_list) enforce the copying of the remote wavefunctions? Retrieve_temporary_list is set to 
`
xmlpaths = os.path.join(calc._OUTPUT_SUBFOLDER, calc._PREFIX + '.save', 'K*[0-9]', 'eigenval*.xml')
retrieve_temporary_list = [[xmlpaths, '.', 2]]
`

**Comment by lekah** [comment] 2018-01-01 13:02
The above comment indeed fixes this problem:
`
xmlpaths = os.path.join('out', 'aiida' + '.save', 'K*[0-9]', 'eigenval*.xml')
retrieve_temporary_list = [[xmlpaths, '.', 2]]
calc_scf._set_retrieve_temporary_list(retrieve_temporary_list)

with transport as open_transport:
    calc_scf.create_input_nodes(open_transport)
    calc_scf.prepare_for_retrieval_and_parsing(open_transport)
`

**Comment by sphuber** [comment] 2018-01-02 19:41
This is a duplicate of #53

**Closed** 2019-08-27 19:59 UTC
Labels: topic/PwImmigrant, topic/calculations, type/duplicate, type/enhancement
