### ISSUE TITLE
`PwBaseWorkChain` failed after multiple iterations

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-quantumespresso#345] opened 2019-06-24 15:25 UTC
With `3dd` branch:

```
(aiida-workshop) ph-tsm15-025:aiida-cjs-working cjs14$ verdi process report 3800
2019-06-23 14:56:00 [339 | REPORT]: [3800|PwRelaxWorkChain|run_relax]: launching PwBaseWorkChain<3803>
2019-06-23 14:56:05 [340 | REPORT]:   [3803|PwBaseWorkChain|run_calculation]: launching PwCalculation<3806> iteration #1
2019-06-24 02:24:19 [344 | REPORT]:   [3803|PwBaseWorkChain|report_error_handled]: PwCalculation<3806> failed with exit status 400: The calculation stopped prematurely because it ran out of walltime.
2019-06-24 02:24:19 [345 | REPORT]:   [3803|PwBaseWorkChain|report_error_handled]: Action taken: simply restart from the last calculation
2019-06-24 02:24:21 [346 | REPORT]:   [3803|PwBaseWorkChain|run_calculation]: launching PwCalculation<3815> iteration #2
2019-06-24 13:53:55 [403 | REPORT]:   [3803|PwBaseWorkChain|report_error_handled]: PwCalculation<3815> failed with exit status 400: The calculation stopped prematurely because it ran out of walltime.
2019-06-24 13:53:55 [404 | REPORT]:   [3803|PwBaseWorkChain|report_error_handled]: Action taken: simply restart from the last calculation
2019-06-24 13:53:55 [405 | REPORT]:   [3803|PwBaseWorkChain|on_except]: Traceback (most recent call last):
  File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/plumpy/process_states.py", line 220, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/Users/cjs14/GitHub/aiida_core_develop/aiida/engine/processes/workchains/workchain.py", line 181, in _do_step
    finished, stepper_result = self._stepper.step()
  File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/plumpy/workchains.py", line 277, in step
    finished, result = self._child_stepper.step()
  File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/plumpy/workchains.py", line 509, in step
    finished, result = self._child_stepper.step()
  File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/plumpy/workchains.py", line 277, in step
    finished, result = self._child_stepper.step()
  File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/plumpy/workchains.py", line 228, in step
    return True, self._fn(self._workchain)
  File "/Users/cjs14/GitHub/aiida-quantumespresso-develop/aiida_quantumespresso/workflows/pw/base.py", line 296, in prepare_calculation
    `restart_mode` is set to `from_scratch`.
KeyError: 'CONTROL'

2019-06-24 13:53:55 [406 | REPORT]:   [3803|PwBaseWorkChain|on_terminated]: remote folders will not be cleaned
2019-06-24 13:53:56 [407 | REPORT]: [3800|PwRelaxWorkChain|inspect_relax]: relax PwBaseWorkChain failed with exit status None
2019-06-24 13:53:56 [408 | REPORT]: [3800|PwRelaxWorkChain|on_terminated]: remote folders will not be cleaned
```

**Comment by sphuber** [comment] 2019-06-24 16:06
Interesting that this happens after the second iteration but not the first, even though the error is exactly the same. The `self.ctx.inputs.parameters` is initialized in `validate_parameters` to always set the `CONTROL` key to empty dictionary if it does not already exist. Somewhere in the code this must be undone then, but I cannot see any code that explicitly alters `self.ctx.inputs.parameters`. Maybe there is a subtle bug with a reference being kept and being altered. Perhaps in the `prepare_process_inputs` utility function. I will try to reproduce this

**Comment by chrisjsewell** [comment] 2019-06-24 16:25
Yeh seems like a reference issue, but can't see where it would occur either?

**Comment by sphuber** [comment] 2019-06-24 16:30
I tried to reproduce by launching a `PwBaseWorkChain` with a low `max-wallclock-seconds`:
```
aiida-quantumespresso workflow launch pw-base -X pw-v6.1 -p SSSP_v1.1_efficiency_PBE -s 103 -w 5 -W 600 -R 1200
```
This hits the OOW handler 5 times and restarts 5 times without problem :confused: 
I have no idea why this would behave differently. Have you seen this behavior more often? Can you reproduce it?

**Comment by chrisjsewell** [comment] 2019-06-24 16:37
No only the once. It had a 12 hour wall time, so not the quickest to reproduce!
I'll let you know if it happens again.

**Comment by chrisjsewell** [comment] 2019-06-26 09:03
I have come across this issue again in a few calculations, these time after `_handle_electronic_convergence_not_achieved` had been called (I don't believe it happens every time though). So it seems that it is something within the `BaseRestartWorkChain._handle_calculation_failure` mechanism that is causing the issue.

**Comment by sphuber** [comment] 2019-06-27 14:56
I just hit this problem as well and it happened directly after a daemon restart, whereas before everything ran smoothly. Is it possible that you also restarted the daemon just before you noticed this exception?

**Comment by chrisjsewell** [comment] 2019-06-27 15:21
Oo yeh quite possibly. That make senses, that maybe it’s an issue with aiida-core/plumpy saving or loading nested dictionaries to the `ctx` checkpoint?

**Comment by sphuber** [comment] 2019-06-27 15:26
that's what I am starting to think. It might have to do something with the recent change to `AttributeDict`, which now recursively creates attribute dicts if a nested dictionary is passed. Now that I think I know how to trigger it, I will see if I can reproduce it locally. Unfortunately I hit this in production :(

**Comment by chrisjsewell** [comment] 2019-06-27 15:30
Well I did try to warn you lol

**Comment by sphuber** [comment] 2019-06-27 15:32
> Well I did try to warn you lol

about `AttributeDicts`? Where?

**Comment by chrisjsewell** [comment] 2019-06-27 15:35
Oh no, just about the WorkChain fails

**Comment by chrisjsewell** [comment] 2019-06-27 15:37
Would never have guessed it was related to `AttributeDicts`! Classic coding, you can write all the unit tests you want, but they'll still be something you don't catch ;(

**Comment by sphuber** [comment] 2019-06-27 15:37
Ah haha yeah, that you did. Very unfortunate, but had to start running. Guess fixing this just got priority :)

**Comment by sphuber** [comment] 2019-06-27 18:14
I think [I have found the culprit](https://github.com/aiidateam/aiida_core/issues/3092) and a solution. Combination of custom YAML serializer/deserializers and the recursive construction behavior of `AttributeDict` :sob: fuck me

**Comment by sphuber** [comment] 2019-06-28 13:28
I am pretty sure the bug reported in this issue was due [this issue in `aiida-core`](https://github.com/aiidateam/aiida_core/issues/3092). The problem was basically due to a combination of the recursive nature of the `AttributeDict` constructor and an incomplete YAML serializer. The latter is used to serialize the state of a `WorkChain` to a string, such that it can be stored as a checkpoint on the process node. This allows a daemon runner to reload it after a restart. The bug ensured that any normal dictionaries nested inside an `AttributeDict` were not correctly deserialized and the content was lost. Since the context of a work chain *is* an `AttributeDict`, any normal dictionaries, like the `parameters` input in this case, lost their content.

This should now be fixed, so I am closing this. If you encounter it again, you can reopen it.

**Closed by sphuber** 2019-06-28 13:28 UTC
Labels: priority/important, topic/workflows, type/bug

**Comment by chrisjsewell** [comment] 2019-06-28 14:29
Thanks @sphuber! 
To update `aiida-core` to this commit (coming after the JSONB merge), I guess I need to migrate my database? Do you think this is "safe" to do (there's no bug fixes in the works)? I guess it would be good if there is a `v1.0.0b5` release at some point, since these are relatively major changes.

**Comment by sphuber** [comment] 2019-06-28 14:35
Yes, since `1.0.0b4` there are two new migrations. One that migrates left-over `state` attributes from old `JobCalculations`, where it converts it to `process_state`, `process_status` and `exit_status attributes. The second migration only affects Django databases. We have tested this extensively on a big production database (8 million nodes) and have not found problems, but never say never of course. If you don't feel safe migrating yet, you can always cherry-pick that commit on top of your local version of `aiida-core` of course. I was hoping that `1.0.0b4` was the last beta, but maybe you are right, since I fixed two major bugs and the big changes in `BackendNode` attributes/extras interface/implementation, maybe another beta is necessary.
